version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm start

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: run semantic release
          command: |
            npm install
            npx semantic-release


workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
